### ISSUE TITLE
Keys directory was not automatically created

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#100]
```
root@metis:/data/metis-gui# yasetnode 10.99.245.5 --skip-setup
Traceback (most recent call last):
  File "/usr/local/bin/yasetnode", line 8, in <module>
    sys.exit(manage_node())
  File "/usr/local/lib/python3.9/dist-packages/yascheduler/utils.py", line 430, in manage_node
    asyncio.run(_manage_node())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/yascheduler/utils.py", line 414, in _manage_node
    client_keys=config.local.get_private_keys(),
  File "/usr/local/lib/python3.9/dist-packages/yascheduler/config/local.py", line 43, in get_private_keys
    return list(filepaths)
  File "/usr/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/data/yadata/keys'
```

**Comment by blokhin** [comment]
@knopki this should be easy to fix

**Comment by blokhin** [comment]
also #127
