### ISSUE TITLE
Azure installation is fragile

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#24]
```
root@corvus:/home/eb# pip install --upgrade azure-mgmt-network
Requirement already up-to-date...
```

but

```
root@corvus:/home/eb# yascheduler
Traceback (most recent call last):
  File "/usr/bin/yascheduler", line 335, in <module>
    daemonize()
  File "/usr/bin/yascheduler", line 254, in daemonize
    yac, clouds = clouds.yascheduler, yac.clouds = Yascheduler(config), CloudAPIManager(config)
  File "/usr/local/lib/python3.8/dist-packages/yascheduler/clouds/__init__.py", line 182, in __init__
    self.apis[name] = load_cloudapi(name)(config)
  File "/usr/local/lib/python3.8/dist-packages/yascheduler/clouds/__init__.py", line 217, in load_cloudapi
    cloudapi_mod = import_module('.' + name, package='yascheduler.clouds')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/yascheduler/clouds/az.py", line 48, in <module>
    from azure.mgmt.network.v2021_03_01 import NetworkManagementClient
ModuleNotFoundError: No module named 'azure.mgmt.network.v2021_03_01'
```

**Comment by blokhin** [comment]
`19.3.0`
