### ISSUE TITLE
paramiko.ssh_exception.SSHException: No authentication methods available

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#47]
On my Linux laptop there is an issue starting scheduler via supervisor:
```
INFO:yascheduler.CloudAPIManager:Active cloud APIs: -
INFO:yascheduler.CloudAPIManager.AllocatorThread[0]:Thread started
INFO:yascheduler.CloudAPIManager.AllocatorThread[1]:Thread started
INFO:yascheduler.CloudAPIManager.DeallocatorThread[0]:Thread started
INFO:yascheduler.CloudAPIManager.DeallocatorThread[1]:Thread started
INFO:Yascheduler.WebhookThread[0]:Thread started
DEBUG:yascheduler:Available computing engines: dummy
Traceback (most recent call last):
  File "/usr/bin/yascheduler", line 619, in <module>
    daemonize()
  File "/usr/bin/yascheduler", line 595, in daemonize
    step()
  File "/usr/bin/yascheduler", line 491, in step
    yac.ssh_connect(all_nodes)
  File "/usr/bin/yascheduler", line 261, in ssh_connect
    self.remote_machines[ip] = MyParamikoMachine.create_machine(
  File "/usr/local/lib/python3.8/dist-packages/yascheduler/ssh.py", line 40, in create_machine
    return connect()
  File "/usr/local/lib/python3.8/dist-packages/plumbum/machines/paramiko_machine.py", line 270, in __init__
    self._client.connect(host, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/usr/local/lib/python3.8/dist-packages/paramiko/client.py", line 767, in _auth
    raise SSHException("No authentication methods available")
paramiko.ssh_exception.SSHException: No authentication methods available
```

Supervisor config is
```
[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[inet_http_server]
port = 127.0.0.1:7060

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:7060
username=
password=

[program:scheduler]
command=/usr/bin/yascheduler
user=postgres
autostart=false
autorestart=true
stderr_logfile=/data/yascheduler.log
stdout_logfile=/data/yascheduler.log
```

```
$ yanodes
ip=127.0.0.1 ncpus=MAX enabled=True occupied_by=- (task_id=-)
```

**Comment by knopki** [comment]
There is no `paramiko` and no `paramiko`'s errors. New errors are implemented in #49.
